### ISSUE TITLE
[Design]- 초기 PPT로 구상한 화면 Figma

### ISSUE THREAD

**Issue by hoeun0723** [PJ-team10/-Object-Oriented-PJ#1]
# About
초기 PPT로 구상한 화면에 대한 디자인입니다. 
Figma로 comment 부탁드립니다.

# Description
기존 ppt로 구상한 부분을 figma에 옮겼습니다.
앱을 만들면서 추가되는 부분이 있을거고, 수정 되는 부분이 있을것이라고 예상하기에 지속적인 comment가 필요하다고 생각합니다.

# 주의사항
Figma 를 수정하며 앞으로 확인을 부탁드릴게 있다면 issue를 계속해서 생성할 예정입니다.
링크를 타고 들어가 관련 comment를 Figma에 저를 @로 언급하여 알려주세요.

# Figma 링크
https://www.figma.com/file/jTYTRI9UpI3aPD1E8uZq5S/Obj-10?node-id=0%3A1

**Comment by Youngseo-Jeon0313** [comment]
너무 좋아용!! 의견 나눠볼 것 메모 남겨놨습니당!
